name: learn-github-actions
on: [push]
jobs:
  environment:
    name: output env
    runs-on: ubuntu-latest
    outputs:
      name: ${{steps.env.outputs.name}}
    steps:
      - name: Output environment
        id: env
        run: echo "name=sennay" >> $GITHUB_OUTPUT
  deploy:
    name: deploy
    needs: [environment]
    runs-on: self-hosted
    steps:
      - name: DOT ENV
        run: echo $HOME/IdeaProjects/.${{needs.environment.outputs.name}}.env > file
