name: learn-github-actions
on: [push]
jobs:
  build:
    name: output env
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Server
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sennayw/nest-casl
  # deploy:
  #   name: deploy
  #   needs: [build]
  #   runs-on: self-hosted
