name: learn-github-actions
on: [push]
jobs:
  build:
    name: output env
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Server
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sennayw/nest-casl
          cache-from: type=registry,ref=sennayw/nest-casl-buildcache
          cache-to: type=registry,ref=sennayw/nest-casl-buildcache,mode=max
  deploy:
    name: deploy
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: pull image
        run: docker pull sennayw/nest-casl

      - name: get pwd
        run: notify-send $PWD

      - name: deployment
        run: docker compose up -d --force-recreate
